### PR TITLE
添加学士学位论文封面支持

### PR DESCRIPTION
**Pull request by gaocegege**
Thank @AlexaraWu for his PR https://github.com/weijianwen/SJTUThesis/pull/201

### CODE REVIEW

**Comment by gaocegege** [comment]
screenshot from 2017-11-09 17-51-13

**Comment by AlexaraWu** [comment]
@gaocegege Do you need a vector graphic of red version logo?

**Comment by gaocegege** [comment]
I'd love to, could you offer it to me? 😄

**Comment by AlexaraWu** [comment]
Here you are: [sjtubanner.pdf](https://github.com/dyweb/SJTUThesis/files/1462332/sjtubanner.pdf).

**Comment by gaocegege** [comment]
Thanks

**Pull request merged**
